from .home import home
from .detail import Detail
from .contact import contact
from .category import CategoryListView
from .my_posts import myPosts
from .addArticle import addArticle
from .updateArticle import updateArticle
from .deleteArticle import DeleteArticle
from .deleteComment import deleteComment
from .deleteComment import deleteComment