from .home import home
from .detail import detail
from .contact import contact
from .category import category
from .my_posts import myPosts
from .addArticle import addArticle
from .updateArticle import updateArticle
from .deleteArticle import deleteArticle
from .deleteComment import deleteComment
from .deleteComment import deleteComment