from .home import home
from .detail import Detail
from .contact import ContactView
from .category import CategoryListView
from .my_posts import myPosts
from .addArticle import AddArticle
from .updateArticle import UpdateArticle
from .deleteArticle import DeleteArticle
from .deleteComment import deleteComment
from .deleteComment import deleteComment